//分类
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
//轮播图
export const SET_HOME_SLIDERS = "SET_HOME_SLIDERS";
//loading
export const GET_HOME_LESSONS_LOADING = "GET_HOME_LESSONS_LOADING";
//课程
export const SET_HOME_LESSONS = "SET_HOME_LESSONS";

export const REFRESH_HOME_LESSONS_LOADING = "REFRESH_HOME_LESSONS_LOADING";

export const REFRESH_HOME_LESSONS = "REFRESH_HOME_LESSONS";

export const SAVE_SESSION = "SAVE_SESSION";
